name: Deploy to itch.io
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: /home/runner/.local/share/godot/builds/Web

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: jdno/setup-butler@v1
      - run: butler push dist shizor/teal-gamejam-25:html5
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}